fixed golangci-lint version compatibility in GitHub Actions
# Description

The "CI" GitHub Action fails with the following error:
```
Running [/home/runner/golangci-lint-1.64.8-linux-amd64/golangci-lint run --out-format=github-actions] in [] ...
  level=warning msg="[config_reader] The output format `github-actions` is deprecated, please use `colored-line-number`"
  Error: you are using a configuration file for golangci-lint v2 with golangci-lint v1: please use golangci-lint v2
  Failed executing command with error: you are using a configuration file for golangci-lint v2 with golangci-lint v1: please use golangci-lint v2
```

The problem is caused by using golangci-lint `v1` with a `v2` configuration file, resulting in linting failures during CI runs.

# Test plan

1. Created a pull request to `main`
2. Observed that the "CI" action completed successfully